package cn.gyyx.elves.scheduler.util.thrift;
/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import java.util.ArrayList;
import java.util.BitSet;
import java.util.Collections;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Generated;

import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-11-11")
public class AgentService {

  public interface Iface {

    public List<Reinstruct> instructionInvokeAsync(List<Instruct> insList) throws org.apache.thrift.TException;

    public Reinstruct instructionInvokeSync(Instruct ins) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void instructionInvokeAsync(List<Instruct> insList, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException;

    public void instructionInvokeSync(Instruct ins, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public List<Reinstruct> instructionInvokeAsync(List<Instruct> insList) throws org.apache.thrift.TException
    {
      send_instructionInvokeAsync(insList);
      return recv_instructionInvokeAsync();
    }

    public void send_instructionInvokeAsync(List<Instruct> insList) throws org.apache.thrift.TException
    {
      instructionInvokeAsync_args args = new instructionInvokeAsync_args();
      args.setInsList(insList);
      sendBase("instructionInvokeAsync", args);
    }

    public List<Reinstruct> recv_instructionInvokeAsync() throws org.apache.thrift.TException
    {
      instructionInvokeAsync_result result = new instructionInvokeAsync_result();
      receiveBase(result, "instructionInvokeAsync");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "instructionInvokeAsync failed: unknown result");
    }

    public Reinstruct instructionInvokeSync(Instruct ins) throws org.apache.thrift.TException
    {
      send_instructionInvokeSync(ins);
      return recv_instructionInvokeSync();
    }

    public void send_instructionInvokeSync(Instruct ins) throws org.apache.thrift.TException
    {
      instructionInvokeSync_args args = new instructionInvokeSync_args();
      args.setIns(ins);
      sendBase("instructionInvokeSync", args);
    }

    public Reinstruct recv_instructionInvokeSync() throws org.apache.thrift.TException
    {
      instructionInvokeSync_result result = new instructionInvokeSync_result();
      receiveBase(result, "instructionInvokeSync");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "instructionInvokeSync failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void instructionInvokeAsync(List<Instruct> insList, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException {
      checkReady();
      instructionInvokeAsync_call method_call = new instructionInvokeAsync_call(insList, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class instructionInvokeAsync_call extends org.apache.thrift.async.TAsyncMethodCall {
      private List<Instruct> insList;
      public instructionInvokeAsync_call(List<Instruct> insList, org.apache.thrift.async.AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.insList = insList;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("instructionInvokeAsync", org.apache.thrift.protocol.TMessageType.CALL, 0));
        instructionInvokeAsync_args args = new instructionInvokeAsync_args();
        args.setInsList(insList);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public List<Reinstruct> getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_instructionInvokeAsync();
      }
    }

    public void instructionInvokeSync(Instruct ins, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException {
      checkReady();
      instructionInvokeSync_call method_call = new instructionInvokeSync_call(ins, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class instructionInvokeSync_call extends org.apache.thrift.async.TAsyncMethodCall {
      private Instruct ins;
      public instructionInvokeSync_call(Instruct ins, org.apache.thrift.async.AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.ins = ins;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("instructionInvokeSync", org.apache.thrift.protocol.TMessageType.CALL, 0));
        instructionInvokeSync_args args = new instructionInvokeSync_args();
        args.setIns(ins);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public Reinstruct getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_instructionInvokeSync();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("instructionInvokeAsync", new instructionInvokeAsync());
      processMap.put("instructionInvokeSync", new instructionInvokeSync());
      return processMap;
    }

    public static class instructionInvokeAsync<I extends Iface> extends org.apache.thrift.ProcessFunction<I, instructionInvokeAsync_args> {
      public instructionInvokeAsync() {
        super("instructionInvokeAsync");
      }

      public instructionInvokeAsync_args getEmptyArgsInstance() {
        return new instructionInvokeAsync_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public instructionInvokeAsync_result getResult(I iface, instructionInvokeAsync_args args) throws org.apache.thrift.TException {
        instructionInvokeAsync_result result = new instructionInvokeAsync_result();
        result.success = iface.instructionInvokeAsync(args.insList);
        return result;
      }
    }

    public static class instructionInvokeSync<I extends Iface> extends org.apache.thrift.ProcessFunction<I, instructionInvokeSync_args> {
      public instructionInvokeSync() {
        super("instructionInvokeSync");
      }

      public instructionInvokeSync_args getEmptyArgsInstance() {
        return new instructionInvokeSync_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public instructionInvokeSync_result getResult(I iface, instructionInvokeSync_args args) throws org.apache.thrift.TException {
        instructionInvokeSync_result result = new instructionInvokeSync_result();
        result.success = iface.instructionInvokeSync(args.ins);
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final Logger LOGGER = LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("instructionInvokeAsync", new instructionInvokeAsync());
      processMap.put("instructionInvokeSync", new instructionInvokeSync());
      return processMap;
    }

    public static class instructionInvokeAsync<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, instructionInvokeAsync_args, List<Reinstruct>> {
      public instructionInvokeAsync() {
        super("instructionInvokeAsync");
      }

      public instructionInvokeAsync_args getEmptyArgsInstance() {
        return new instructionInvokeAsync_args();
      }

      public AsyncMethodCallback<List<Reinstruct>> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<List<Reinstruct>>() { 
          public void onComplete(List<Reinstruct> o) {
            instructionInvokeAsync_result result = new instructionInvokeAsync_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            instructionInvokeAsync_result result = new instructionInvokeAsync_result();
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, instructionInvokeAsync_args args, org.apache.thrift.async.AsyncMethodCallback<List<Reinstruct>> resultHandler) throws TException {
        iface.instructionInvokeAsync(args.insList,resultHandler);
      }
    }

    public static class instructionInvokeSync<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, instructionInvokeSync_args, Reinstruct> {
      public instructionInvokeSync() {
        super("instructionInvokeSync");
      }

      public instructionInvokeSync_args getEmptyArgsInstance() {
        return new instructionInvokeSync_args();
      }

      public AsyncMethodCallback<Reinstruct> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<Reinstruct>() { 
          public void onComplete(Reinstruct o) {
            instructionInvokeSync_result result = new instructionInvokeSync_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            instructionInvokeSync_result result = new instructionInvokeSync_result();
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, instructionInvokeSync_args args, org.apache.thrift.async.AsyncMethodCallback<Reinstruct> resultHandler) throws TException {
        iface.instructionInvokeSync(args.ins,resultHandler);
      }
    }

  }

  public static class instructionInvokeAsync_args implements org.apache.thrift.TBase<instructionInvokeAsync_args, instructionInvokeAsync_args._Fields>, java.io.Serializable, Cloneable, Comparable<instructionInvokeAsync_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("instructionInvokeAsync_args");

    private static final org.apache.thrift.protocol.TField INS_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("insList", org.apache.thrift.protocol.TType.LIST, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new instructionInvokeAsync_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new instructionInvokeAsync_argsTupleSchemeFactory());
    }

    public List<Instruct> insList; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      INS_LIST((short)1, "insList");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // INS_LIST
            return INS_LIST;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.INS_LIST, new org.apache.thrift.meta_data.FieldMetaData("insList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
              new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Instruct.class))));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(instructionInvokeAsync_args.class, metaDataMap);
    }

    public instructionInvokeAsync_args() {
    }

    public instructionInvokeAsync_args(
      List<Instruct> insList)
    {
      this();
      this.insList = insList;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public instructionInvokeAsync_args(instructionInvokeAsync_args other) {
      if (other.isSetInsList()) {
        List<Instruct> __this__insList = new ArrayList<Instruct>(other.insList.size());
        for (Instruct other_element : other.insList) {
          __this__insList.add(new Instruct(other_element));
        }
        this.insList = __this__insList;
      }
    }

    public instructionInvokeAsync_args deepCopy() {
      return new instructionInvokeAsync_args(this);
    }

    @Override
    public void clear() {
      this.insList = null;
    }

    public int getInsListSize() {
      return (this.insList == null) ? 0 : this.insList.size();
    }

    public java.util.Iterator<Instruct> getInsListIterator() {
      return (this.insList == null) ? null : this.insList.iterator();
    }

    public void addToInsList(Instruct elem) {
      if (this.insList == null) {
        this.insList = new ArrayList<Instruct>();
      }
      this.insList.add(elem);
    }

    public List<Instruct> getInsList() {
      return this.insList;
    }

    public instructionInvokeAsync_args setInsList(List<Instruct> insList) {
      this.insList = insList;
      return this;
    }

    public void unsetInsList() {
      this.insList = null;
    }

    /** Returns true if field insList is set (has been assigned a value) and false otherwise */
    public boolean isSetInsList() {
      return this.insList != null;
    }

    public void setInsListIsSet(boolean value) {
      if (!value) {
        this.insList = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case INS_LIST:
        if (value == null) {
          unsetInsList();
        } else {
          setInsList((List<Instruct>)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case INS_LIST:
        return getInsList();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case INS_LIST:
        return isSetInsList();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof instructionInvokeAsync_args)
        return this.equals((instructionInvokeAsync_args)that);
      return false;
    }

    public boolean equals(instructionInvokeAsync_args that) {
      if (that == null)
        return false;

      boolean this_present_insList = true && this.isSetInsList();
      boolean that_present_insList = true && that.isSetInsList();
      if (this_present_insList || that_present_insList) {
        if (!(this_present_insList && that_present_insList))
          return false;
        if (!this.insList.equals(that.insList))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_insList = true && (isSetInsList());
      list.add(present_insList);
      if (present_insList)
        list.add(insList);

      return list.hashCode();
    }

    @Override
    public int compareTo(instructionInvokeAsync_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetInsList()).compareTo(other.isSetInsList());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetInsList()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.insList, other.insList);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("instructionInvokeAsync_args(");
      boolean first = true;

      sb.append("insList:");
      if (this.insList == null) {
        sb.append("null");
      } else {
        sb.append(this.insList);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class instructionInvokeAsync_argsStandardSchemeFactory implements SchemeFactory {
      public instructionInvokeAsync_argsStandardScheme getScheme() {
        return new instructionInvokeAsync_argsStandardScheme();
      }
    }

    private static class instructionInvokeAsync_argsStandardScheme extends StandardScheme<instructionInvokeAsync_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, instructionInvokeAsync_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // INS_LIST
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                  struct.insList = new ArrayList<Instruct>(_list0.size);
                  Instruct _elem1;
                  for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                  {
                    _elem1 = new Instruct();
                    _elem1.read(iprot);
                    struct.insList.add(_elem1);
                  }
                  iprot.readListEnd();
                }
                struct.setInsListIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, instructionInvokeAsync_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.insList != null) {
          oprot.writeFieldBegin(INS_LIST_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.insList.size()));
            for (Instruct _iter3 : struct.insList)
            {
              _iter3.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class instructionInvokeAsync_argsTupleSchemeFactory implements SchemeFactory {
      public instructionInvokeAsync_argsTupleScheme getScheme() {
        return new instructionInvokeAsync_argsTupleScheme();
      }
    }

    private static class instructionInvokeAsync_argsTupleScheme extends TupleScheme<instructionInvokeAsync_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, instructionInvokeAsync_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetInsList()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetInsList()) {
          {
            oprot.writeI32(struct.insList.size());
            for (Instruct _iter4 : struct.insList)
            {
              _iter4.write(oprot);
            }
          }
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, instructionInvokeAsync_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
            struct.insList = new ArrayList<Instruct>(_list5.size);
            Instruct _elem6;
            for (int _i7 = 0; _i7 < _list5.size; ++_i7)
            {
              _elem6 = new Instruct();
              _elem6.read(iprot);
              struct.insList.add(_elem6);
            }
          }
          struct.setInsListIsSet(true);
        }
      }
    }

  }

  public static class instructionInvokeAsync_result implements org.apache.thrift.TBase<instructionInvokeAsync_result, instructionInvokeAsync_result._Fields>, java.io.Serializable, Cloneable, Comparable<instructionInvokeAsync_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("instructionInvokeAsync_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.LIST, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new instructionInvokeAsync_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new instructionInvokeAsync_resultTupleSchemeFactory());
    }

    public List<Reinstruct> success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
              new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Reinstruct.class))));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(instructionInvokeAsync_result.class, metaDataMap);
    }

    public instructionInvokeAsync_result() {
    }

    public instructionInvokeAsync_result(
      List<Reinstruct> success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public instructionInvokeAsync_result(instructionInvokeAsync_result other) {
      if (other.isSetSuccess()) {
        List<Reinstruct> __this__success = new ArrayList<Reinstruct>(other.success.size());
        for (Reinstruct other_element : other.success) {
          __this__success.add(new Reinstruct(other_element));
        }
        this.success = __this__success;
      }
    }

    public instructionInvokeAsync_result deepCopy() {
      return new instructionInvokeAsync_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public int getSuccessSize() {
      return (this.success == null) ? 0 : this.success.size();
    }

    public java.util.Iterator<Reinstruct> getSuccessIterator() {
      return (this.success == null) ? null : this.success.iterator();
    }

    public void addToSuccess(Reinstruct elem) {
      if (this.success == null) {
        this.success = new ArrayList<Reinstruct>();
      }
      this.success.add(elem);
    }

    public List<Reinstruct> getSuccess() {
      return this.success;
    }

    public instructionInvokeAsync_result setSuccess(List<Reinstruct> success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((List<Reinstruct>)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof instructionInvokeAsync_result)
        return this.equals((instructionInvokeAsync_result)that);
      return false;
    }

    public boolean equals(instructionInvokeAsync_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      return list.hashCode();
    }

    @Override
    public int compareTo(instructionInvokeAsync_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("instructionInvokeAsync_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class instructionInvokeAsync_resultStandardSchemeFactory implements SchemeFactory {
      public instructionInvokeAsync_resultStandardScheme getScheme() {
        return new instructionInvokeAsync_resultStandardScheme();
      }
    }

    private static class instructionInvokeAsync_resultStandardScheme extends StandardScheme<instructionInvokeAsync_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, instructionInvokeAsync_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                  struct.success = new ArrayList<Reinstruct>(_list8.size);
                  Reinstruct _elem9;
                  for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                  {
                    _elem9 = new Reinstruct();
                    _elem9.read(iprot);
                    struct.success.add(_elem9);
                  }
                  iprot.readListEnd();
                }
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, instructionInvokeAsync_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.success.size()));
            for (Reinstruct _iter11 : struct.success)
            {
              _iter11.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class instructionInvokeAsync_resultTupleSchemeFactory implements SchemeFactory {
      public instructionInvokeAsync_resultTupleScheme getScheme() {
        return new instructionInvokeAsync_resultTupleScheme();
      }
    }

    private static class instructionInvokeAsync_resultTupleScheme extends TupleScheme<instructionInvokeAsync_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, instructionInvokeAsync_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          {
            oprot.writeI32(struct.success.size());
            for (Reinstruct _iter12 : struct.success)
            {
              _iter12.write(oprot);
            }
          }
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, instructionInvokeAsync_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
            struct.success = new ArrayList<Reinstruct>(_list13.size);
            Reinstruct _elem14;
            for (int _i15 = 0; _i15 < _list13.size; ++_i15)
            {
              _elem14 = new Reinstruct();
              _elem14.read(iprot);
              struct.success.add(_elem14);
            }
          }
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

  public static class instructionInvokeSync_args implements org.apache.thrift.TBase<instructionInvokeSync_args, instructionInvokeSync_args._Fields>, java.io.Serializable, Cloneable, Comparable<instructionInvokeSync_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("instructionInvokeSync_args");

    private static final org.apache.thrift.protocol.TField INS_FIELD_DESC = new org.apache.thrift.protocol.TField("ins", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new instructionInvokeSync_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new instructionInvokeSync_argsTupleSchemeFactory());
    }

    public Instruct ins; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      INS((short)1, "ins");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // INS
            return INS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.INS, new org.apache.thrift.meta_data.FieldMetaData("ins", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Instruct.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(instructionInvokeSync_args.class, metaDataMap);
    }

    public instructionInvokeSync_args() {
    }

    public instructionInvokeSync_args(
      Instruct ins)
    {
      this();
      this.ins = ins;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public instructionInvokeSync_args(instructionInvokeSync_args other) {
      if (other.isSetIns()) {
        this.ins = new Instruct(other.ins);
      }
    }

    public instructionInvokeSync_args deepCopy() {
      return new instructionInvokeSync_args(this);
    }

    @Override
    public void clear() {
      this.ins = null;
    }

    public Instruct getIns() {
      return this.ins;
    }

    public instructionInvokeSync_args setIns(Instruct ins) {
      this.ins = ins;
      return this;
    }

    public void unsetIns() {
      this.ins = null;
    }

    /** Returns true if field ins is set (has been assigned a value) and false otherwise */
    public boolean isSetIns() {
      return this.ins != null;
    }

    public void setInsIsSet(boolean value) {
      if (!value) {
        this.ins = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case INS:
        if (value == null) {
          unsetIns();
        } else {
          setIns((Instruct)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case INS:
        return getIns();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case INS:
        return isSetIns();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof instructionInvokeSync_args)
        return this.equals((instructionInvokeSync_args)that);
      return false;
    }

    public boolean equals(instructionInvokeSync_args that) {
      if (that == null)
        return false;

      boolean this_present_ins = true && this.isSetIns();
      boolean that_present_ins = true && that.isSetIns();
      if (this_present_ins || that_present_ins) {
        if (!(this_present_ins && that_present_ins))
          return false;
        if (!this.ins.equals(that.ins))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_ins = true && (isSetIns());
      list.add(present_ins);
      if (present_ins)
        list.add(ins);

      return list.hashCode();
    }

    @Override
    public int compareTo(instructionInvokeSync_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetIns()).compareTo(other.isSetIns());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetIns()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ins, other.ins);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("instructionInvokeSync_args(");
      boolean first = true;

      sb.append("ins:");
      if (this.ins == null) {
        sb.append("null");
      } else {
        sb.append(this.ins);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (ins != null) {
        ins.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class instructionInvokeSync_argsStandardSchemeFactory implements SchemeFactory {
      public instructionInvokeSync_argsStandardScheme getScheme() {
        return new instructionInvokeSync_argsStandardScheme();
      }
    }

    private static class instructionInvokeSync_argsStandardScheme extends StandardScheme<instructionInvokeSync_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, instructionInvokeSync_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // INS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.ins = new Instruct();
                struct.ins.read(iprot);
                struct.setInsIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, instructionInvokeSync_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.ins != null) {
          oprot.writeFieldBegin(INS_FIELD_DESC);
          struct.ins.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class instructionInvokeSync_argsTupleSchemeFactory implements SchemeFactory {
      public instructionInvokeSync_argsTupleScheme getScheme() {
        return new instructionInvokeSync_argsTupleScheme();
      }
    }

    private static class instructionInvokeSync_argsTupleScheme extends TupleScheme<instructionInvokeSync_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, instructionInvokeSync_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetIns()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetIns()) {
          struct.ins.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, instructionInvokeSync_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.ins = new Instruct();
          struct.ins.read(iprot);
          struct.setInsIsSet(true);
        }
      }
    }

  }

  public static class instructionInvokeSync_result implements org.apache.thrift.TBase<instructionInvokeSync_result, instructionInvokeSync_result._Fields>, java.io.Serializable, Cloneable, Comparable<instructionInvokeSync_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("instructionInvokeSync_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new instructionInvokeSync_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new instructionInvokeSync_resultTupleSchemeFactory());
    }

    public Reinstruct success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Reinstruct.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(instructionInvokeSync_result.class, metaDataMap);
    }

    public instructionInvokeSync_result() {
    }

    public instructionInvokeSync_result(
      Reinstruct success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public instructionInvokeSync_result(instructionInvokeSync_result other) {
      if (other.isSetSuccess()) {
        this.success = new Reinstruct(other.success);
      }
    }

    public instructionInvokeSync_result deepCopy() {
      return new instructionInvokeSync_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public Reinstruct getSuccess() {
      return this.success;
    }

    public instructionInvokeSync_result setSuccess(Reinstruct success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((Reinstruct)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof instructionInvokeSync_result)
        return this.equals((instructionInvokeSync_result)that);
      return false;
    }

    public boolean equals(instructionInvokeSync_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      return list.hashCode();
    }

    @Override
    public int compareTo(instructionInvokeSync_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("instructionInvokeSync_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (success != null) {
        success.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class instructionInvokeSync_resultStandardSchemeFactory implements SchemeFactory {
      public instructionInvokeSync_resultStandardScheme getScheme() {
        return new instructionInvokeSync_resultStandardScheme();
      }
    }

    private static class instructionInvokeSync_resultStandardScheme extends StandardScheme<instructionInvokeSync_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, instructionInvokeSync_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new Reinstruct();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, instructionInvokeSync_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class instructionInvokeSync_resultTupleSchemeFactory implements SchemeFactory {
      public instructionInvokeSync_resultTupleScheme getScheme() {
        return new instructionInvokeSync_resultTupleScheme();
      }
    }

    private static class instructionInvokeSync_resultTupleScheme extends TupleScheme<instructionInvokeSync_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, instructionInvokeSync_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, instructionInvokeSync_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = new Reinstruct();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

}
